Individual exercise
Siffster85/OneTwoTrain pull request #12
Opened 2024-03-27 15:13 UTC by Karumu05

2024-03-27 15:25 UTC, Siffster85 approved these changes

2024-03-27 16:01 UTC, elenatrr requested changes

2024-03-27 16:01 UTC, elenatrr commented on app/(tabs)/plan/addExercise.tsx
> +  const [nextButtonNav, setNextButtonNav] = useState(false);
booleans are usually named with "is" or "are" at the start, so could you rename this variable, example: "isNextBtnShown"

2024-03-27 16:01 UTC, elenatrr commented on app/(tabs)/plan/addExercise.tsx
> +          ]}
I would initialise a variable with these items and labels above the return keyword where all your const variables are, so here instead of a huge array you can pass only the variable (for code readability)

2024-03-27 16:01 UTC, elenatrr commented on app/(tabs)/plan/addExercise.tsx
> +          ]}
these items as well

2024-03-27 16:01 UTC, elenatrr commented on app/(tabs)/plan/exercises/[id].tsx
> +      <View style={{ flex: 3 }}>
It would be better to follow same styling pattern - adding classes instead of putting values in html. This will make it easier for us to style the elements in the future.

2024-03-27 16:01 UTC, elenatrr commented on app/(tabs)/plan/exercises/[id].tsx
> +  const setQuantity = 3;
I would rename this variable getting rid of "set" to avoid misunderstanding (usually we use "set" in "useState")

2024-03-27 16:01 UTC, elenatrr commented on app/(tabs)/plan/index.tsx
> +  return <Redirect href="/plan/home" />;
Let's get rid of this component, as there is no point in redirection, we can send user directly to "/plan/home"

2024-03-27 16:01 UTC, elenatrr commented on app/(tabs)/plan/timer.tsx
> +  const [key, setKey] = useState(0);
could you rename "key" variable, pls, because its not clear what key it is

2024-03-27 16:01 UTC, elenatrr commented on app/(tabs)/plan/timer.tsx
> +            }
could you put this whole expression in a declared function, pls

2024-03-27 16:01 UTC, elenatrr commented on components/CustomButton.tsx
> +            borderRadius: 150,
could you insert the styles into a class instead of adding the values in html tag

2024-03-27 16:01 UTC, elenatrr commented on components/CustomButton.tsx
> +          style={[styles.button, { backgroundColor: '#fff' }]}
same here

2024-03-27 16:01 UTC, elenatrr commented on components/CustomButton.tsx
> +          <Text style={[styles.buttonLabel, { color: '#25292e' }]}>
and here, could you fix it in the  whole file

2024-03-27 16:36 UTC, Karumu05 commented on app/(tabs)/plan/timer.tsx
> +  const [key, setKey] = useState(0);
Key is set like this due to the functionality of the countDownTimer. 
Key is what we use to reset the countDown, so I am following the pattern of the dev who made the component.

2024-03-27 16:55 UTC, elenatrr commented on app/(tabs)/plan/addExercise.tsx
> +  const [nextButtonNav, isNextButtonNav] = useState(false);
maybe const [isNextButtonNav, setIsNextButtonNav] = useState(false); ?

2024-03-27 16:55 UTC, elenatrr commented on app/(tabs)/plan/exercises/[id].tsx
> +  const Quantity = 3;
i guess it should be lowercased const quantity = 3;

2024-03-28 09:20 UTC, elenatrr approved these changes

2024-03-28 09:20 UTC, merged