Id5 button
Siffster85/OneTwoTrain pull request #13
Opened 2024-03-27 15:21 UTC by Siffster85

2024-03-27 16:21 UTC, elenatrr requested changes

2024-03-27 16:21 UTC, elenatrr commented on components/PlaceholderComponent.tsx
> +export default PlaceholderComponent;
I would recommend you to rename this components, because it's not really clear what placeholder component does. It looks more like button, so is it possible to reuse custom button instead of creating a new one?

2024-03-27 16:21 UTC, elenatrr commented on components/PlaceholderComponent.tsx
> +export default PlaceholderComponent;
And also we decided to name the pages inside app folder from lower case

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/ChangePassword.tsx
> +  const user: any = auth.currentUser;
it's better to avoid type of any

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/ChangePassword.tsx
> +  const [reset, setReset] = useState(false);
boolean values usually start with "is" or "are", e.g. isReset

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/ChangePassword.tsx
> +  const newPassword = password;
can you rename password on line 14 to newPassword? so you can get rid of this line

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/ChangePassword.tsx
> +    if (!reset) {
what is reset for? do we really need this variable?

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/ChangePassword.tsx
> +export default ChangePassword;
I recommend you to run **npm run lint**  to check if there are any warnings is the whole code. If there are, you should fix them manually before making a commit.

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/ChangePassword.tsx
> +    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
It would be better to follow same styling pattern - adding classes instead of putting values in html tags. This will make it easier for us to style the elements in the future.

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/ChangePassword.tsx
> +        <Button title="Change Password" onPress={handleSubmit} />
onPress={changePassword} ? for better readability

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/DeleteProfile.tsx
> +  const user: any = auth.currentUser;
it's better to avoid type any. Does it return error when you do not specify the type herE?

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/DeleteProfile.tsx
> +  const credential: any = EmailAuthProvider.credential(user.email, password);
same here

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/DeleteProfile.tsx
> +    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
style should be in a class

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/index.tsx
> +      </View>
Can you make this code drier? I would put all the text in an array and map through this array, leaving only two View tags in my code:
     <View style={styles.LCol}>
        <Text style={styles.text}>Date of Birth</Text>
      </View>
      <View style={styles.RCol}>
        <Text style={styles.text}>{userProfile.dateofbirth}</Text>
      </View>

2024-03-27 16:21 UTC, elenatrr commented on app/(tabs)/profile/index.tsx
are you sure that userProfileTypes and userProfile must be here? I would declare them on top where all the const variables are.

2024-03-27 16:21 UTC, elenatrr commented on components/PlaceholderComponent.tsx
> +        style={[styles.button, { backgroundColor: 'red' }]}
can you add backgroundColor: 'red' to the button class?

2024-03-27 16:21 UTC, elenatrr commented on components/PlaceholderComponent.tsx
> +          paddingTop: 10,
can you add all the values to buttonContainer class?

2024-03-27 16:25 UTC, Karumu05 approved these changes

2024-03-28 11:11 UTC, Karumu05 approved these changes

2024-03-28 11:17 UTC, elenatrr commented on app/(tabs)/profile/index.tsx
> +              key={'a' + data}
'a' + data is type coercion which is not recommended to do (now we add string to an array, as I understand). I'd better set key as index, or key = {data[0]}
 
{profileData.map(data, index => {
          return (
            <View
              key={index}
   ...

2024-03-28 11:17 UTC, elenatrr commented on app/(tabs)/profile/index.tsx
> +                paddingBottom: 5,
Could you put these values in a class?

2024-03-28 11:22 UTC, elenatrr approved these changes

2024-03-28 11:28 UTC, merged